version: '2'
services:
    onlineshopping-app:
        image: onlineshopping
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://onlineshopping-mysql:3306/onlineshopping?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    onlineshopping-mysql:
        extends:
            file: mysql.yml
            service: onlineshopping-mysql
